2016-05-19 11:40:38
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/status.py", line 552, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1054, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 694, in write
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/win32.py", line 183, in write
BufferError: Error writing to console: The handle is invalid.
2016-05-19 11:45:56
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 92, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1062, in do_checkout
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1148, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 694, in write
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/win32.py", line 183, in write
BufferError: Error writing to console: The handle is invalid.
2016-05-19 11:47:26
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 92, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1062, in do_checkout
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1148, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 694, in write
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/win32.py", line 183, in write
BufferError: Error writing to console: The handle is invalid.
2016-06-30 13:35:39
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 92, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/listeners.py", line 253, in do_operation
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1054, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 694, in write
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/win32.py", line 183, in write
BufferError: Error writing to console: The handle is invalid.
2016-06-30 13:36:39
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/status.py", line 552, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1054, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 694, in write
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/win32.py", line 183, in write
BufferError: Error writing to console: The handle is invalid.
